# TODO: remove these when run_exports are added to the packages.
pin_run_as_build:
  gazebo:
    max_pin: x
  libpcap:
    max_pin: x.x
  log4cxx:
    max_pin: x.x.x
  opencv:
    max_pin: x.x
  pcl:
    max_pin: x.x.x

console_bridge:
  - 1.0
gazebo:
  - '11'
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.16   # [not (osx and arm64)]
  # - 1.16   # [not (osx and arm64)]
  # - 1.16   # [not (osx and arm64)]
  - 1.19   # [osx and arm64]
ogre:
  - 1.10.12
opencv:
  - 4.5
pcl:
  - 1.11.1
python:
  # part of a zip_keys: python, python_impl, numpy
  # - 3.6.* *_cpython    # [not (osx and arm64)]
  # - 3.7.* *_cpython    # [not (osx and arm64)]
  - 3.8.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  # - cpython   # [not (osx and arm64)]
  # - cpython   # [not (osx and arm64)]
  - cpython

# Project overrides
macos_min_version:             # [osx]
  - 10.14                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.14                      # [osx]
